apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uszribx37-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uszribx37-python 
  name: uszribx37-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uszribx37-python 
